<?php

// This file was generated by running "composer dump-env prod"

return array (
  'SYMFONY_DOTENV_PATH' => './.env',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
