<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '55d48d02773b0728decde0a3df5c57766196de04aecf18a0f042875191ac4af6',
  'DATABASE_URL' => 'mysql://hh11gyhxc1zr7fpn:vyxaz2ktz1kod355@ryfqldzbliwmq6g5.chr7pe7iynqr.eu-west-1.rds.amazonaws.com:3306/j8rzl3t5htv5k9s5',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
